# Configuración de Netlify
[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/article/:id"
  to   = "/.netlify/functions/og-meta"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
